# Generated by Django 5.0.6 on 2024-06-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetups',
            options={'verbose_name_plural': 'Meetup'},
        ),
        migrations.AddField(
            model_name='meetups',
            name='image',
            field=models.ImageField(default=None, upload_to='images'),
            preserve_default=False,
        ),
    ]
