# Generated by Django 5.0.6 on 2024-06-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_alter_meetups_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetups',
            name='date',
            field=models.DateField(default='2021-02-21'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetups',
            name='organizer',
            field=models.EmailField(default='test@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
